---
- name: Test HTTPS connectivity (port 443) via ansible.builtin.uri
  hosts: all
  gather_facts: false
  tasks:

    - name: Attempt connection to port 443
      ansible.builtin.uri:
        url: "https://{{ inventory_hostname }}"
        method: HEAD
        validate_certs: false           # â† change to true in production
        follow_redirects: safe
        return_content: no
        timeout: 7
      delegate_to: localhost
      register: https_check
      failed_when: false
      changed_when: false

    - name: Show result
      ansible.builtin.debug:
        msg: >
          {% if https_check.status == 200 or https_check.status == 401 or https_check.status == 403 -%}
          Port 443 is OPEN and responded (status {{ https_check.status }})
          {%- elif https_check.status is defined -%}
          Port 443 is OPEN but returned HTTP {{ https_check.status }}
          {%- else -%}
          Port 443 is NOT reachable ({{ https_check.msg | default('connection failed') }})
          {%- endif %}
      when: https_check is defined